### ISSUE TITLE
Add the ability to set the output volume to be greater than 100%

### ISSUE THREAD

**Issue by johnhoran** [johnhoran/Laine#1]

**Comment by JockeTF** [comment]
If you add support for this, then please make sure it is configurable. I can see why people who use laptop speakers would like this. But, for those with a proper sound system, accidentally setting the volume above maximum would do nothing but worsen the audio quality.

**Comment by johnhoran** [comment]
Yeah if I add it, it will be as an option that has to be enabled in a settings dialog.  And even then I would want the slider to have a "notch", like the slider in the settings dialog has.  Which might require a custom slider.  So I'm not going to add it, unless I can get all that in place.
