### ISSUE TITLE
Oh, hi there!

### ISSUE THREAD

**Issue by aleho** [johnhoran/Laine#10]
I just discovered your extension and initial reason for developing it.

My reasons were exactly the same, which gave birth to Shell Volume Mixer [1] some time ago.

Currently I'm about the only developer of SVM and I though two extensions trying to solve the same problem in roughly the same way seems a bit of an overkill.

So what would you say, join forces? (and userbases ;)

[1] https://github.com/aleho/gnome-shell-volume-mixer

**Comment by johnhoran** [comment]
Hey,
well I'd certainly welcome any collaboration.  What are you proposing?
