### ISSUE TITLE
Merged View in Gnome 3.16

### ISSUE THREAD

**Issue by ramesh45345** [johnhoran/Laine#12]
Not sure if you've seen this, but it seems like Laine in Gnome 3.16 doesn't merge with the main drop down menu (in the top right hand corner). There is a small audio menu next to the drop-down menu for all Laine functions. I notice that the screenshots show the merged view, however I can't seem to enable it in the options or anything like that. Is this planned to be re-enabled? I'm using Arch Linux, which recently upgraded to Gnome 3.16 in the stable repositories.

**Comment by johnhoran** [comment]
Hi, I actually have always had the volume slider in a separate dropdown.  I figured it would be less cluttered, especially on a laptop where there can be a bunch of other stuff in that menu.  So if you have seen screenshots showing it all in a single menu, then they must be from a different extension, perhaps [gnome-shell-volume-mixer](https://github.com/aleho/gnome-shell-volume-mixer).  

In any case, I do think it might be relatively simple to add this as a feature to my extension.  So I'm going to mark this as an enhancement, and I'll see what it looks like when I get a chance to implement it.

**Comment by jonnius** [comment]
I would really appreciate to see this feature!

**Comment by tobimensch** [comment]
+1

Pretty please.

**Comment by srihari93** [comment]
Hi, I am using Gnome 3.18 and cannot merge the volume controls into the aggregate menu with the version in [Gnome Extensions](https://extensions.gnome.org/extension/937/laine/). This feature seems to be added over an year ago. Am I missing a dependency here or is this a bug? Would appreciate the help.
