### ISSUE TITLE
Removal of selected USB device breaks extension until restart

### ISSUE THREAD

**Issue by johnhoran** [johnhoran/Laine#19]
I actually strongly suspect that this is a bug in the Pulseaudio DBus interface, as I can trigger it there without having the extension loaded.  But if you have a USB sound card selected and then physically remove it, pulseaudio then cannot set, or advertise any fallback sink changes through its DBus interface.  

Manually removing the dbus module and reloading it also fixes this error.

The aim of this report is mostly to say that I'm aware and looking into this issue.

**Comment by eduardohki** [comment]
Hi,

Here is the same for me. I'm running Fedora 23.

**Comment by johnhoran** [comment]
Finally found some time to mess around with this again.  And yes it was caused by a bug in the DBus interface.  I've submitted a patch to pulseaudio, so if it is accepted, then that should fix it.
[[PATCH] module-dbus: fix for module incorrectly believing no sinks or sources are available on device disconnection.](https://lists.freedesktop.org/archives/pulseaudio-discuss/2016-March/025723.html)
