### ISSUE TITLE
Should not depend on PlaybackStatus to reset the timer on song change.

### ISSUE THREAD

**Issue by JasonLG1979** [johnhoran/Laine#27]
I admittedly know very little about js and how GNOME shell extensions are written but judging from this:

```
else if(key == 'PlaybackStatus'){
                        let state = val.get_string()[0];
                        if(state == 'Playing'){
                            this._setStatePlaying();
                        }
                        else {
                            if (this._sigUpdPos != 0) {
                                Loop.source_remove(this._sigUpdPos);
                                this._sigUpdPos = 0;
                            }
                            this._playBtn.child.icon_name = 'media-playback-start-symbolic';        
                        }
```

And this

```
    _setStatePlaying: function(){
        this._playBtn.child.icon_name = 'media-playback-pause-symbolic';

        this._dbus.call(this._path, '/org/mpris/MediaPlayer2', "org.freedesktop.DBus.Properties", "Get",
            GLib.Variant.new('(ss)', ['org.mpris.MediaPlayer2.Player', 'Position']), GLib.VariantType.new("(v)"),
            Gio.DBusCallFlags.NONE, -1, null, Lang.bind(this, function(conn, query){
                try{
                    let response = conn.call_finish(query).get_child_value(0).unpack();
                    this._mediaPosition = response.get_int64();

                    if(this._sigUpdPos == 0)
                        this._sigUpdPos = Loop.timeout_add_seconds(1, Lang.bind(this, this._updatePosition));
                } catch(err){
                    //not all players support position (e.g. Nuvola) so if this exception is thrown, do nothing.
                    if(!err.message.startsWith("GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such property"))
                        throw err;
                }
            })
        );
        this._dbus.call(this._path, '/org/mpris/MediaPlayer2', "org.freedesktop.DBus.Properties", "Get",
            GLib.Variant.new('(ss)', ['org.mpris.MediaPlayer2.Player', 'Rate']), GLib.VariantType.new("(v)"),
            Gio.DBusCallFlags.NONE, -1, null, Lang.bind(this, function(conn, query){
                try{
                    let response = conn.call_finish(query).get_child_value(0).unpack();
                    this._mediaRate = response.get_double();
                } catch(err){
                    //not all players support rate (e.g. Nuvola) so if this exception is thrown, do nothing.
                    if(!err.message.startsWith("GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such property"))
                        throw err;
                }
            })
        );
    },
```

The extension seems to create  a new timer on a PlaybackStatus of "Playing" and destroy the timer on "Paused" or "Stopped"(the 2 other valid PlaybackStatus values) The problem is that if a player goes from song to song without changing it's PlaybackStatus the timer is never reset. Essentially the extension uses PlaybackStatus to determine that the song has changed. It is very possible for a player to change songs without leaving a "Playing" state which breaks your position slider.

It would be better to depend on mpris:trackid to determine that the song has changed, as it is suppose to be unique for each track and by spec is absolutely suppose to be in the metadata.

From the spec:

> The mpris:trackid attribute must always be present, and must be of D-Bus type "o".

**Comment by johnhoran** [comment]
Yeah, that's a very valid point.  Truth be told I know very little about the mpris spec, or indeed gnome extensions, so everything is a little hacky.  I'll take your advice, and switch it over it using the trackid.

**Comment by JasonLG1979** [comment]
I know very little about it myself. It's really hard to find a "reference" implementation of MPRIS. Everyone seems to do it a little different.(kinda defeats the point of a spec,lol!!!)

The other GNOME media extension uses trackUrl to determine song changes. So you might want to do a "if trackId or trackUrl is different it's a different song." To cover the bases.

**Comment by johnhoran** [comment]
Sure, can do.  Thanks for the advice.

**Comment by johnhoran** [comment]
That should do it.  I just query the time when the trackid changes.  Obviously that means that I'll be asking for the time twice if the player actually does change the playbackstatus, but that doesn't matter much.

Can you test that and see it it works with a player that doesn't change the playback status?

**Comment by JasonLG1979** [comment]
> Can you test that and see it it works with a player that doesn't change the playback status?

That seems to do the trick. Thanks!!!
