### ISSUE TITLE
PopupSubMenuMenuItem error

### ISSUE THREAD

**Issue by lucazade** [johnhoran/Laine#30]
I get this error when I open the popup menu.

`mar 15 22:28:39 archos gnome-session[803]: (gnome-shell:894): Gjs-WARNING **: JS ERROR: Exception in callback for signal: open-state-changed: TypeError: this._getTopMenu(...)._setOpenedSubMenu is not a function
mar 15 22:28:39 archos gnome-session[803]: PopupSubMenuMenuItem<._subMenuOpenStateChanged@resource:///org/gnome/shell/ui/popupMenu.js:1092
mar 15 22:28:39 archos gnome-session[803]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 22:28:39 archos gnome-session[803]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
mar 15 22:28:39 archos gnome-session[803]: PopupSubMenu<.open@resource:///org/gnome/shell/ui/popupMenu.js:918
mar 15 22:28:39 archos gnome-session[803]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 22:28:39 archos gnome-session[803]: PopupSubMenuMenuItem<.setSubmenuShown@resource:///org/gnome/shell/ui/popupMenu.js:1111
mar 15 22:28:39 archos gnome-session[803]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 22:28:39 archos gnome-session[803]: PopupSubMenuMenuItem<._setOpenState@resource:///org/gnome/shell/ui/popupMenu.js:1117
mar 15 22:28:39 archos gnome-session[803]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 22:28:39 archos gnome-session[803]: PopupSubMenuMenuItem<._onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:1147
mar 15 22:28:39 archos gnome-session[803]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 22:28:41 archos gnome-session[803]: (gnome-shell:894): Gjs-WARNING **: JS ERROR: Exception in callback for signal: open-state-changed: TypeError: this._getTopMenu(...)._setOpenedSubMenu is not a function
mar 15 22:28:41 archos gnome-session[803]: PopupSubMenuMenuItem<._subMenuOpenStateChanged@resource:///org/gnome/shell/ui/popupMenu.js:1097
mar 15 22:28:41 archos gnome-session[803]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 22:28:41 archos gnome-session[803]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
mar 15 22:28:41 archos gnome-session[803]: PopupSubMenu<.close@resource:///org/gnome/shell/ui/popupMenu.js:971
mar 15 22:28:41 archos gnome-session[803]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 22:28:41 archos gnome-session[803]: PopupMenuBase<.addMenuItem/closingId<@resource:///org/gnome/shell/ui/popupMenu.js:654
mar 15 22:28:41 archos gnome-session[803]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
mar 15 22:28:41 archos gnome-session[803]: PopupMenuBase<.addMenuItem/parentClosingId<@resource:///org/gnome/shell/ui/popupMenu.js:632
mar 15 22:28:41 archos gnome-session[803]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
mar 15 22:28:41 archos gnome-session[803]: PopupMenu<.close/<@resource:///org/gnome/shell/ui/popupMenu.js:834
mar 15 22:28:41 archos gnome-session[803]: BoxPointer<.hide/<.onComplete<@resource:///org/gnome/shell/ui/boxpointer.js:165
mar 15 22:28:41 archos gnome-session[803]: _addHandler/params[name]@resource:///org/gnome/shell/ui/tweener.js:91
mar 15 22:28:41 archos gnome-session[803]: _callOnFunction@resource:///org/gnome/gjs/modules/tweener/tweener.js:203
mar 15 22:28:41 archos gnome-session[803]: _updateTweenByIndex@resource:///org/gnome/gjs/modules/tweener/tweener.js:333
mar 15 22:28:41 archos gnome-session[803]: _updateTweens@resource:///org/gnome/gjs/modules/tweener/tweener.js:345
mar 15 22:28:41 archos gnome-session[803]: _onEnterFrame@resource:///org/gnome/gjs/modules/tweener/tweener.js:360
mar 15 22:28:41 archos gnome-session[803]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
mar 15 22:28:41 archos gnome-session[803]: ClutterFrameTicker<._onNewFrame@resource:///org/gnome/shell/ui/tweener.js:208
mar 15 22:28:41 archos gnome-session[803]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 22:28:41 archos gnome-session[803]: ClutterFrameTicker<._init/<@resource:///org/gnome/shell/ui/tweener.js:183
`

**Comment by johnhoran** [comment]
Um, it looks like I should include that method and use it to close a submenu when another one is opened.  Thanks for the report.
