### ISSUE TITLE
unable to handle remote url (http) for album art, e.g., in spotify-clien for ubunto/fedora

### ISSUE THREAD

**Issue by Jerry-Ma** [johnhoran/Laine#33]
Hi,

Thank you for this fabulous extension, it obsoletes a number of other ones and is the best to my taste!
However I found that it does not play well with Spotify-client, due to the latter's strange mpris implementation.
Briefly speaking, the `artUrl` value emitted from spotify is a remote url that points to a jpg file, when this is the case the album art is not correctly loaded. I made my attempts to retrieve the data using Soup however I am not proficient enough to solve the problem. (I posted my attempted code to stackoverflow: http://stackoverflow.com/questions/36465340/gjs-gnome-shell-extension-read-remote-jpg-image-from-url-and-set-as-icon)

**Comment by johnhoran** [comment]
Sure, I'll take a look.

**Comment by johnhoran** [comment]
Seems to work on spotify now.
