### ISSUE TITLE
Microphone not appearing in Laine

### ISSUE THREAD

**Issue by mathomp4** [johnhoran/Laine#37]
Hello. I have to say I love Laine, but I don't seem to know how to configure it. 

I recently got a webcam for my Linux box (Logitech c920 HD Pro) and it has a microphone in it. I can definitely use the microphone as the GNOME settings show it responding and a Skype call (miraculously on Linux) worked and the other end could hear me.

But, Laine only shows volume and not microphone. Is there an extra toggle somewhere I need to flip?

**Comment by johnhoran** [comment]
Hey,
It should become visible when you have something that's listening to it.  I
take it that isn't happening?

**Comment by mathomp4** [comment]
Well, an unexpected reboot later and now I _do_ have a microphone slider when recording (say in Cheese). I guess it was just some hiccup somewhere. Sorry to bother!

**Comment by johnhoran** [comment]
Hey no problem, its always a work in progress, so I appreciate any bugs people report.

**Comment by mathomp4** [comment]
Yeah. I suppose when I first tried, I was hoping the microphone control was _always_ there. That way I could disable it when I'm feeling paranoid (sadly, my camera's "I'm working" light is only enabled when the camera is on, not the microphone!)
