### ISSUE TITLE
Update for Version 3.22.1

### ISSUE THREAD

**Issue by james-nesbitt** [johnhoran/Laine#38]
Can you please update the plugin matedata.json version to match the latest gnome release, version 3.22.1

**Comment by anika200** [comment]
In case it helps someone,
Use the download button and then unpack Laine-master.zip. Enter the directory /Laine-master/src/ and open the file metadata.json and change the line "shell-version": [ "3.22.2" ], to match your shell version, save and close the file. Now open a terminal in /Laine-master and type "make" then "make install". You are done, now restart Gnome Shell "alt-F2" and type "r" and hit enter.
