### ISSUE TITLE
Icon doesn't change to headphones.

### ISSUE THREAD

**Issue by johnhoran** [johnhoran/Laine#4]
It used to change to headphones, or an audio card, depending on the type of active output device.  Just noticed it doesn't any more

**Comment by ghost** [comment]
Can confirm, this would be nice to have.

**Comment by johnhoran** [comment]
Was just looking into this, and I don't think this is actually a bug in my code, rather the icon pack I'm using just doesn't have an icon for audio-headphones-symbolic, and so it defaults to the generic speaker.  Switching back to the default icon packs, such as gnome or adwaita, result in the icon changing correctly again.

**Comment by johnhoran** [comment]
I'm reopening this.  I think I need to figure out a different way of figuring out if the output is speakers or headphones, as I suspect my current approach is dependant on English being the chosen language (I was literally checking if a string was equals headphones)

**Comment by johnhoran** [comment]
Okay I think this should work regardless of the users selected language, like so:
![head](https://cloud.githubusercontent.com/assets/3147650/7135812/4a3251c6-e2a2-11e4-8374-12d92a09135a.png)

So I'm closing this again until I hear otherwise.
