### ISSUE TITLE
Show labels above sound card slider

### ISSUE THREAD

**Issue by johnhoran** [johnhoran/Laine#8]
Add the ability to view a labels describing the active sink above the slider.  This is something that the user would have to enable in the preferences.

**Comment by ghost** [comment]
There is problem with this and output switcher - you can't adjust volume with keyboard in menu using right arrow.

Splitting output switcher to sepatate line would be better in my opinion.

Half year ago I made mockups of GNOME menus, so maybe you find some of elements interesting too.

![system status menu](https://raw.githubusercontent.com/chpii/design/master/menus/1-system-status-menu.png)
![playback](https://raw.githubusercontent.com/chpii/design/master/menus/2-playback.png)

I will try to mock up it in context to your extension on a weekend.

**Comment by johnhoran** [comment]
I agree that the right arrow not being able to adjust the volume is an issue.  But I think I should be able remove the binding for the arrow keys from the dropdown and put them on the slider instead.  The dropdown would still be accessible by pressing enter.
